<?php

declare(strict_types=1);

return [
    'filtering' => [
        'kill_list' => [
            'title_keywords' => [
                'audiobook',
                'audio cd',
                'mp3',
                'narrated by',
                'unabridged',
                'box set',
                'boxed set',
                'complete collection',
                'omnibus',
                'summary of',
                'analysis of',
                'study guide',
                'trivia',
                'coloring book',
                'movie tie-in',
                'now a major motion picture',
                'netflix',
                'large print',
            ],
            'subtitle_keywords' => [
                'audiobook',
                'audio cd',
                'narrated by',
                'unabridged',
                'box set',
                'boxed set',
                'complete collection',
                'omnibus',
                'summary of',
                'analysis of',
                'study guide',
                'trivia',
                'coloring book',
                'movie tie-in',
                'now a major motion picture',
                'netflix',
                'large print',
            ],
            'publisher_keywords' => [
                'audible',
                'recorded books',
                'brilliance',
                'listening library',
                'books on tape',
                'blackstone audio',
                'tantor',
            ],
        ],
        'allowed_languages' => ['en', 'eng', 'english', ''],
        'excluded_formats' => [
            'audiobook',
            'audio cd',
            'audio',
            'cd',
            'mp3',
            'cassette',
        ],
    ],

    'edition_scoring' => [
        'format_boosts' => [
            'hardcover' => 50,
            'hardback' => 50,
            'trade paperback' => 35,
            'paperback' => 30,
            'mass market paperback' => 25,
            'ebook' => 40,
            'kindle' => 40,
            'epub' => 40,
            'electronic' => 40,
            'digital' => 40,
        ],
        'publisher_tiers' => [
            'premium' => [
                'scholastic' => 200,
                'random house' => 180,
                'penguin' => 170,
                'simon & schuster' => 160,
                'simon and schuster' => 160,
                'harpercollins' => 150,
                'harper collins' => 150,
                'little, brown' => 140,
                'little brown' => 140,
                'doubleday' => 130,
                'knopf' => 130,
                'alfred a. knopf' => 130,
                'putnam' => 120,
                'viking' => 120,
            ],
            'quality' => [
                'macmillan' => 80,
                'hachette' => 80,
                'bloomsbury' => 70,
                'tor' => 70,
                'tor books' => 70,
                'del rey' => 70,
                'bantam' => 60,
                'ace' => 60,
                'ace books' => 60,
                'berkley' => 60,
                'vintage' => 50,
                'anchor' => 50,
                'orbit' => 50,
                'daw' => 50,
                'daw books' => 50,
            ],
        ],
        'boosts' => [
            'has_isbn13' => 40,
            'has_isbn10' => 30,
            'first_edition_era' => 50,
            'multiple_covers' => 10,
            'english_language' => 5,
        ],
        'penalties' => [
            'movie_tie_in' => -30,
            'no_isbn' => -20,
        ],
        'year_boosts' => [
            '2000-2005' => 50,
            '1990-1999' => 45,
            '2006-2010' => 25,
            '2011-2015' => 10,
        ],
    ],

    'cover_quality' => [
        'min_width' => 200,
        'min_height' => 300,
        'min_file_size_bytes' => 5000,
        'head_min_content_length' => 5000,
        'aspect_ratio_min' => 1.3,
        'aspect_ratio_max' => 1.7,
    ],

    'cover_sources' => [
        'open_library_large' => [
            'url_pattern' => 'https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg',
            'priority' => 1,
        ],
        'google_books_high_res' => [
            'fife_param' => 'w1000',
            'priority' => 2,
        ],
        'primary_cover' => [
            'priority' => 3,
        ],
        'fallback_cover' => [
            'priority' => 4,
        ],
    ],
];
