/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Semantic tokens - resolve via CSS variables set by ThemeProvider
        canvas: 'var(--color-canvas)',
        surface: 'var(--color-surface)',
        'surface-alt': 'var(--color-surface-alt)',
        'surface-hover': 'var(--color-surface-hover)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        foreground: 'var(--color-foreground)',
        'foreground-muted': 'var(--color-foreground-muted)',
        'foreground-subtle': 'var(--color-foreground-subtle)',
        accent: 'var(--color-accent)',
        success: 'var(--color-success)',
        danger: 'var(--color-danger)',
        warning: 'var(--color-warning)',
        'on-primary': 'var(--color-on-primary)',
        'on-danger': 'var(--color-on-danger)',
        border: 'var(--color-border)',
        'border-hover': 'var(--color-border-hover)',
        'border-muted': 'var(--color-border-muted)',
        paper: 'var(--color-paper)',
        'tint-primary': 'var(--color-tint-primary)',
        'tint-accent': 'var(--color-tint-accent)',
        'tint-green': 'var(--color-tint-green)',
        'tint-yellow': 'var(--color-tint-yellow)',
        'tint-peach': 'var(--color-tint-peach)',
        'tint-beige': 'var(--color-tint-beige)',
        'primary-dark': 'var(--color-primary-dark)',
        'primary-glow': 'var(--color-primary-glow)',
        'foreground-faint': 'var(--color-foreground-faint)',
        'foreground-warm': 'var(--color-foreground-warm)',
        'accent-warm': 'var(--color-accent-warm)',
        'accent-light': 'var(--color-accent-light)',

        // Static Scholar colors (Dark Academia)
        scholar: {
          canvas: '#12100e',
          surface: '#1c1a17',
          'surface-alt': '#161412',
          'surface-hover': '#2a2622',
          primary: '#8b2e2e',
          'primary-hover': '#a33a3a',
          foreground: '#dcd0c0',
          'foreground-muted': '#8c857b',
          'foreground-subtle': '#5c554b',
          border: '#2a2622',
          'border-hover': '#3d3630',
          accent: '#0f172a',
          success: '#4a6741',
          danger: '#8b2e2e',
          paper: '#dcd0c0',
        },

        // Static Dreamer colors (Lavender Cottage)
        dreamer: {
          canvas: '#fbfaf8',
          surface: '#ffffff',
          'surface-alt': '#f3eff5',
          'surface-hover': '#ece7f0',
          primary: '#8b7a9e',
          'primary-hover': '#7a698d',
          foreground: '#4a4550',
          'foreground-muted': '#6b6575',
          'foreground-subtle': '#8b8095',
          border: '#ddd6e0',
          'border-hover': '#c9bfd0',
          accent: '#8aa090',
          success: '#6b9075',
          danger: '#b86b78',
          paper: '#ffffff',
          'tint-green': '#f0f5f2',
          'tint-yellow': '#f8f4e8',
          'tint-peach': '#fcf0ed',
          'tint-beige': '#f4f0e8',
        },
      },
      fontFamily: {
        // Scholar fonts
        'playfair': ['PlayfairDisplay'],
        'crimson': ['CrimsonText'],
        // Dreamer fonts
        'nunito': ['Nunito'],
      },
    },
  },
  plugins: [],
};
