import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 8,
  tables: [
    tableSchema({
      name: 'series',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'author', type: 'string' },
        { name: 'external_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'external_provider', type: 'string', isOptional: true },
        { name: 'total_volumes', type: 'number', isOptional: true },
        { name: 'is_complete', type: 'boolean' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'books',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'external_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'external_provider', type: 'string', isOptional: true },
        { name: 'series_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'server_series_id', type: 'number', isOptional: true },
        { name: 'volume_number', type: 'number', isOptional: true },
        { name: 'volume_title', type: 'string', isOptional: true },
        { name: 'title', type: 'string' },
        { name: 'author', type: 'string' },
        { name: 'cover_url', type: 'string', isOptional: true },
        { name: 'local_cover_path', type: 'string', isOptional: true },
        { name: 'page_count', type: 'number', isOptional: true },
        { name: 'height_cm', type: 'number', isOptional: true },
        { name: 'width_cm', type: 'number', isOptional: true },
        { name: 'thickness_cm', type: 'number', isOptional: true },
        { name: 'isbn', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'genres_json', type: 'string', isOptional: true },
        { name: 'published_date', type: 'string', isOptional: true },
        { name: 'audience', type: 'string', isOptional: true },
        { name: 'intensity', type: 'string', isOptional: true },
        { name: 'moods_json', type: 'string', isOptional: true },
        { name: 'is_classified', type: 'boolean', isOptional: true },
        { name: 'classification_confidence', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'user_books',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'book_id', type: 'string', isIndexed: true },
        { name: 'server_book_id', type: 'number', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'rating', type: 'number', isOptional: true },
        { name: 'current_page', type: 'number' },
        { name: 'format', type: 'string', isOptional: true },
        { name: 'price', type: 'number', isOptional: true },
        { name: 'is_pinned', type: 'boolean' },
        { name: 'queue_position', type: 'number', isOptional: true },
        { name: 'review', type: 'string', isOptional: true },
        { name: 'is_dnf', type: 'boolean' },
        { name: 'dnf_reason', type: 'string', isOptional: true },
        { name: 'started_at', type: 'number', isOptional: true },
        { name: 'finished_at', type: 'number', isOptional: true },
        { name: 'custom_cover_url', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'pending_cover_upload', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'tags',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'slug', type: 'string', isIndexed: true },
        { name: 'color', type: 'string' },
        { name: 'is_system', type: 'boolean' },
        { name: 'sort_order', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'user_book_tags',
      columns: [
        { name: 'user_book_id', type: 'string', isIndexed: true },
        { name: 'tag_id', type: 'string', isIndexed: true },
        { name: 'server_user_book_id', type: 'number', isOptional: true },
        { name: 'server_tag_id', type: 'number', isOptional: true },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'read_throughs',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'user_book_id', type: 'string', isIndexed: true },
        { name: 'server_user_book_id', type: 'number', isOptional: true },
        { name: 'read_number', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'rating', type: 'number', isOptional: true },
        { name: 'review', type: 'string', isOptional: true },
        { name: 'is_dnf', type: 'boolean' },
        { name: 'dnf_reason', type: 'string', isOptional: true },
        { name: 'started_at', type: 'number', isOptional: true },
        { name: 'finished_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'reading_sessions',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'user_book_id', type: 'string', isIndexed: true },
        { name: 'server_user_book_id', type: 'number', isOptional: true },
        { name: 'read_through_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'server_read_through_id', type: 'number', isOptional: true },
        { name: 'date', type: 'string' },
        { name: 'pages_read', type: 'number' },
        { name: 'start_page', type: 'number' },
        { name: 'end_page', type: 'number' },
        { name: 'duration_seconds', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'sync_metadata',
      columns: [
        { name: 'key', type: 'string', isIndexed: true },
        { name: 'last_pulled_at', type: 'number' },
        { name: 'last_pushed_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'user_preferences',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'value', type: 'string' },
        { name: 'normalized', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'reading_goals',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true, isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'period', type: 'string' },
        { name: 'target', type: 'number' },
        { name: 'year', type: 'number', isIndexed: true },
        { name: 'month', type: 'number', isOptional: true },
        { name: 'week', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean', isIndexed: true },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_pending_sync', type: 'boolean' },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
  ],
});
