<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\AudienceEnum;
use App\Enums\ContentIntensityEnum;
use App\Models\Author;
use App\Models\Book;
use App\Models\Series;
use App\Services\SeedData\SeedDataService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * Seeds the database from pre-processed CSV files and media.
 *
 * This seeder uses data generated by the seed-data:build-* commands,
 * which have already fetched and processed data from external APIs.
 *
 * Run after migrate:fresh to restore enriched data.
 */
class MasterDataSeeder extends Seeder
{
    private const MEDIA_BASE_PATH = 'database/seeders/data';

    public function __construct(
        private readonly SeedDataService $seedData
    ) {}

    public function run(): void
    {
        $this->command->info('Seeding from pre-processed data files...');

        $stats = $this->seedData->getStats();
        $this->command->table(
            ['Type', 'CSV Records', 'Media Files'],
            collect($stats)->map(fn ($s, $type) => [$type, $s['csv_records'], $s['media_files']])->toArray()
        );

        $this->seedAuthors();
        $this->seedSeries();
        $this->seedBooks();
    }

    /**
     * Seed authors from CSV.
     */
    private function seedAuthors(): void
    {
        $authors = $this->seedData->readCsv('authors');

        if (empty($authors)) {
            $this->command->warn('No authors to seed.');

            return;
        }

        $this->command->info('Seeding '.count($authors).' authors...');

        $createdCount = 0;
        $photoCopiedCount = 0;

        foreach ($authors as $row) {
            $existing = Author::where('slug', $row['slug'])->first();

            if ($existing) {
                continue;
            }

            $photoPath = null;

            if (! empty($row['photo_filename'])) {
                $photoPath = $this->copyMediaToStorage('authors', $row['photo_filename']);

                if ($photoPath) {
                    $photoCopiedCount++;
                }
            }

            Author::create([
                'name' => $row['name'],
                'slug' => $row['slug'],
                'sort_name' => $row['sort_name'] ?: null,
                'open_library_key' => $row['open_library_key'] ?: null,
                'photo_url' => $row['photo_url'] ?: null,
                'photo_path' => $photoPath,
                'metadata' => $this->buildAuthorMetadata($row),
                'source' => 'seed',
            ]);

            $createdCount++;
        }

        $this->command->info("Created {$createdCount} authors, copied {$photoCopiedCount} photos.");
    }

    /**
     * Seed series from CSV.
     */
    private function seedSeries(): void
    {
        $books = $this->seedData->readCsv('books');

        if (empty($books)) {
            return;
        }

        $seriesNames = collect($books)
            ->pluck('series_name')
            ->filter()
            ->unique()
            ->values();

        if ($seriesNames->isEmpty()) {
            $this->command->info('No series to seed.');

            return;
        }

        $this->command->info('Seeding '.$seriesNames->count().' series...');

        $createdCount = 0;

        foreach ($seriesNames as $seriesName) {
            $slug = Str::slug($seriesName);
            $existing = Series::where('slug', $slug)->first();

            if ($existing) {
                continue;
            }

            $seriesBooks = collect($books)->filter(fn ($b) => $b['series_name'] === $seriesName);
            $firstBook = $seriesBooks->first();

            Series::create([
                'title' => $seriesName,
                'slug' => $slug,
                'author' => $firstBook['author'] ?? null,
                'total_volumes' => $seriesBooks->max('volume_number') ?: null,
            ]);

            $createdCount++;
        }

        $this->command->info("Created {$createdCount} series.");
    }

    /**
     * Seed books from CSV.
     */
    private function seedBooks(): void
    {
        $books = $this->seedData->readCsv('books');

        if (empty($books)) {
            $this->command->warn('No books to seed.');

            return;
        }

        $this->command->info('Seeding '.count($books).' books...');

        $createdCount = 0;
        $coverCopiedCount = 0;

        foreach ($books as $row) {
            $identifier = $row['isbn13'] ?: $row['isbn'] ?: Str::slug($row['title']);
            $existing = Book::where('isbn', $row['isbn'])
                ->orWhere('isbn13', $row['isbn13'])
                ->first();

            if ($existing) {
                continue;
            }

            $coverPath = null;

            if (! empty($row['cover_filename'])) {
                $coverPath = $this->copyMediaToStorage('covers', $row['cover_filename']);

                if ($coverPath) {
                    $coverCopiedCount++;
                }
            }

            $seriesId = null;

            if (! empty($row['series_name'])) {
                $series = Series::where('slug', Str::slug($row['series_name']))->first();
                $seriesId = $series?->id;
            }

            $moods = null;

            if (! empty($row['moods'])) {
                $moods = array_map('trim', explode(',', $row['moods']));
            }

            Book::create([
                'isbn' => $row['isbn'] ?: null,
                'isbn13' => $row['isbn13'] ?: null,
                'title' => $row['title'],
                'author' => $row['author'],
                'description' => $row['description'] ?: null,
                'page_count' => ! empty($row['page_count']) ? (int) $row['page_count'] : null,
                'published_date' => ! empty($row['published_date']) ? $row['published_date'] : null,
                'publisher' => $row['publisher'] ?: null,
                'cover_url' => $row['cover_url'] ?: null,
                'cover_path' => $coverPath,
                'series_id' => $seriesId,
                'volume_number' => ! empty($row['volume_number']) ? (int) $row['volume_number'] : null,
                'genres' => ! empty($row['genres']) ? array_map('trim', explode(',', $row['genres'])) : null,
                'audience' => ! empty($row['audience']) ? AudienceEnum::tryFrom($row['audience']) : null,
                'intensity' => ! empty($row['intensity']) ? ContentIntensityEnum::tryFrom($row['intensity']) : null,
                'moods' => $moods,
                'classification_confidence' => ! empty($row['classification_confidence']) ? (float) $row['classification_confidence'] : null,
                'is_classified' => ! empty($row['audience']),
            ]);

            $createdCount++;
        }

        $this->command->info("Created {$createdCount} books, copied {$coverCopiedCount} covers.");
    }

    /**
     * Copy media file from seed data to storage.
     */
    private function copyMediaToStorage(string $type, string $filename): ?string
    {
        $sourcePath = base_path(self::MEDIA_BASE_PATH."/{$type}/{$filename}");

        if (! file_exists($sourcePath)) {
            $sourcePath = base_path(self::MEDIA_BASE_PATH."/books/{$type}/{$filename}");
        }

        if (! file_exists($sourcePath)) {
            $sourcePath = base_path(self::MEDIA_BASE_PATH."/authors/{$type}/{$filename}");
        }

        if (! file_exists($sourcePath)) {
            return null;
        }

        $destType = $type === 'photos' ? 'authors' : 'covers';
        $destPath = "media/{$destType}/{$filename}";

        $contents = file_get_contents($sourcePath);
        Storage::disk('public')->put($destPath, $contents);

        return $filename;
    }

    /**
     * Build author metadata array from CSV row.
     */
    private function buildAuthorMetadata(array $row): ?array
    {
        $metadata = [];

        if (! empty($row['birth_date'])) {
            $metadata['birth_date'] = $row['birth_date'];
        }

        if (! empty($row['death_date'])) {
            $metadata['death_date'] = $row['death_date'];
        }

        if (! empty($row['bio'])) {
            $metadata['bio'] = $row['bio'];
        }

        if (! empty($row['top_work'])) {
            $metadata['top_work'] = $row['top_work'];
        }

        if (! empty($row['work_count'])) {
            $metadata['work_count'] = (int) $row['work_count'];
        }

        if (! empty($row['wikipedia_url'])) {
            $metadata['wikipedia_url'] = $row['wikipedia_url'];
        }

        return ! empty($metadata) ? $metadata : null;
    }
}
